apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: nfs-provisioner_role_binding
subjects:                                                                 #Role Binding for EKS Cluster
  - kind: ServiceAccount
    name: default
    namespace: myekscluster1
roleRef:
  kind: ClusterRole
  name: cluster_admin
  apiGroup: rbac.authorization.k8s.io
  ############################################################################################
