apiVersion: v1
kind: Service
metadata:
  name: wordpress_mysql
  labels:
    app: wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress                   #MYSQL is deployed using service type "ClusterIP" which does not allows outside connectivity as MYSQL is having sensitive data
    tier: mysql
  clusterIP: None
  #####################################################################################
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wordpress_mysql
  labels:
    app: wordpress
spec:                              
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  strategy:
    type: Recreate                           #Deploying MYSQL using its image and its environment variables and adding PVC to it
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:                                        #secret values are created in a secret file which I am not sharing but it can be easily created
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: efs-mysql
############################################################################################################
